// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace __3xPlus1
{
    public partial class MLModelGolds
    {
        /// <summary>
        /// model input class for MLModelGolds.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Gold_Price_USD_per_Ounce")]
            public float Gold_Price_USD_per_Ounce { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelGolds.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Gold_Price_USD_per_Ounce")]
            public float[] Gold_Price_USD_per_Ounce { get; set; }

            [ColumnName(@"Gold_Price_USD_per_Ounce_LB")]
            public float[] Gold_Price_USD_per_Ounce_LB { get; set; }

            [ColumnName(@"Gold_Price_USD_per_Ounce_UB")]
            public float[] Gold_Price_USD_per_Ounce_UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"C:\Users\luwan\OneDrive\Documents\UNI\BCAD3\FINAL SEMESTER\PROG7312\_3xPlus1\_3xPlus1\Classes\MLModelGolds.zip");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

