// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModelGolds_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // predict with default option.
            var modelOutput = MLModelGolds.Predict();
            Console.WriteLine(string.Join(",", modelOutput.Gold_Price_USD_per_Ounce));

            // predict next 5 periods
            modelOutput = MLModelGolds.Predict(horizon: 5);
            Console.WriteLine(string.Join(",", modelOutput.Gold_Price_USD_per_Ounce));

            // update and predict model
            // TBD
        }
    }
}

